### ISSUE TITLE
Main released 1.10.3/1.11.1

### ISSUE THREAD

**Issue by nicktimko** [mathiasertl/fabric#12]
Seems like an easy enough merge.

**Comment by cjw296** [comment]
Actually, this is needed to fix a bug, see #14.

**Comment by mathiasertl** [comment]
I already was working on this a while back, I hit a py3 bug in paramiko, I'll see if this is fixed and I can finally make a release in the next days (I have a free weekend starting tomorrow).

**Comment by mathiasertl** [comment]
... not really an easy merge, but now finally done. :-)
