### ISSUE TITLE
paramiko 2.0 release breaks Fabric 3

### ISSUE THREAD

**Issue by cjw296** [mathiasertl/fabric#14]
Fabric has an undeclared dependency on PyCrypto.

paramiko looks like it's lost it's dependency on PyCrypto as of it's 2.0 release, so you now get the following exception with a few virtualenv install of Fabric3:

```
  File ".../site-packages/fabric/decorators.py", line 8, in <module>
    from Crypto import Random
ImportError: No module named Crypto
```

@bitprophet has fixed this upstream by [pinning to paramiko<2.0](https://pypi.python.org/pypi/Fabric/1.11.1).

Fabric3 should do the same.

**Comment by mathiasertl** [comment]
Hmm - that's somewhat of a disappointment. The reason I haven't ported Fabric 1.11.1 is that paramiko 1.6 (at least the version from a few weeks ago) didn't work with Python 3. I saw the 2.0 release today and was hoping that this would fix the issue.

Does Fabric3 work for you if you manually install pycrypto and paramiko>=2.0? It seems to be that this would be a solution as well.

**Comment by cjw296** [comment]
Can you not just pin paramiko <2.0? This just seems like a no brainer to me...

**Comment by mathiasertl** [comment]
I absolutely can pin paramiko <2.0 - only paramiko 1.6 wasn't working for me in Python 3 either. So it doesn't seem like a very good solution.

**Comment by mathiasertl** [comment]
The new release 1.11.1.post1 pins paramiko to <2.0!

**Comment by cjw296** [comment]
Yep, that fixed it, thanks!

/cc @sejeff

**Comment by bitprophet** [comment]
None of this makes sense to me, by the way - Paramiko has supported Python 3 since 1.13 and up & if there are Python 3 issues they're bugs and likely easily fixed ones.

(If someone is literally on paramiko **1.6** that's incredibly old, I'm guessing y'all meant 1.16?)

**Comment by SEJeff** [comment]
Yeah we definitely got bitten by the paramiko 2 upgrade. Can't wait for invoke to come out and then we can just use that :)

**Comment by bitprophet** [comment]
Indeed. Hoping to hit 1.0 in the aftermath of Pycon/sprints.

**Comment by SEJeff** [comment]
@bitprophet: meetup IRL with @cjw296 @ pycon to collect :beers: from me. Our mutual employer is a pycon sponsor.

**Comment by mathiasertl** [comment]
@bitprophet yes, I meant 1.16. It was a dict_keys[slice] kind of thing, where you'd do

```
some_dict.keys()[3:]
```

.. which works in py2, but not in py3. There were several issues & pull requests already on it, so I didn't report it again. And the upgrade to 1.17.0 fixed the issue (so I assume one of the pull requests got merged ;-)). I can look up the exact details if you want, but I think since the bug is fixed, it's not really worth the effort.

**Comment by bitprophet** [comment]
@mathiasertl Yea that was a bugfix that rolled out in 1.15.5, 1.16.1 and 1.17.0 :)
