### ISSUE TITLE
Publish releases on PyPI

### ISSUE THREAD

**Issue by jaraco** [mathiasertl/fabric#2]
Per [this comment](https://github.com/fabric/fabric/pull/996#issuecomment-163705694), I propose that Fabric3 releases be published on PyPI.

I would have posted an issue here earlier, but I believe that issues were disabled or not visible to me to create them. It's possible that I twice falsely thought that there was no issue tracker for this project, as when I arrived here today, I thought that issues were still disabled because I was looking at the wrong part of the UI.

Nevertheless, at this point, I'm content to maintain releases under Fabric3bis and probably won't switch back to Fabric3 unless I can have access to make releases. If this project does decide to make public releases, I recommend using the technique that I used in Fabric3bis, which re-uses the same Fabric version numbers, but adds a post-release tag to indicate which release following the upstream release. For example [Fabric3bis 1.10.2.post1](https://github.com/jaraco/fabric/tree/1.10.2.post1) is the first Fabric3bis release of Fabric 1.10.2.

I'm extremely grateful for this fork - it's enabled me to use Python 3 exclusively in my full tool chain.

**Comment by mathiasertl** [comment]
Yes, issues for some reason where disabled, which was not my intent, I wasn't even aware that issues could be disabled, hence I didn't check. They are enabled now, sorry for the inconvenience.

The issue I have right now is that not all test-cases apply in python 2:

```
======================================================================
FAIL: test_utils.test_abort_message_only_printed_once
abort()'s SystemExit should not cause a reprint of the error message
----------------------------------------------------------------------
Traceback (most recent call last):  
  File "/home/mati/git/mati/fabric/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mati/git/mati/fabric/tests/test_utils.py", line 101, in test_abort_message_only_printed_once
    eq_(result.stderr, "Fatal error: It burns!\n\nAborting.")
AssertionError: '/bin/sh: 1: fab: not found' != 'Fatal error: It burns!\n\nAborting.'
```

and I'm trying to investigate this issue now.

**Comment by mathiasertl** [comment]
`pip install Fabric3` :-)

**Comment by rodrigc** [comment]
Thanks @mathiasertl , ```pip install Fabric3``` worked for me.
@jaraco: I don't think your fork on PyPy is needed any more, but that is up to you if you want to keep it.
