### ISSUE TITLE
Windows installation doesn't work with Python 3.5

### ISSUE THREAD

**Issue by kbarnes3** [mathiasertl/fabric#21]
This is the same issue as #10 and I agree it isn't an issue with Fabric, but I wanted to call it out again as its still a problem. Specifically, this was fixed in the PyCrypto GitHub repo over 3 years ago:

https://github.com/dlitz/pycrypto/commit/10abfc8633bac653eda4d346fc051b2f07554dcd

And there hasn't been a PyPi update since then. It'd be nice if there was some workaround so people wouldn't have to know to specify a dependency on a package like:

git+https://github.com/dlitz/pycrypto.git@v2.7a1#egg=pycrypto

I don't know what the best solution would be, but I wanted you to know about this.

**Comment by dougthor42** [comment]
It looks like PyCrypto is no longer being maintained. The last update to the git repo was on June 20, 2014.

Perhaps it would be prudent to port to a different crytpo library. My suggestion is [Cryptography](https://cryptography.io/en/latest/), but I haven't done the legwork to see if it has all the things that `Fabric` needs.

In fact, I went ahead and submitted issue fabric/fabric#1540 which suggests this very thing.

**Comment by dougthor42** [comment]
Whoops, looks like they already support Cryptography.

@kbarnes3 Have you tried updating paramiko? Doing that worked for me.

```
python -m pip install --upgrade paramiko
```

**Comment by kbarnes3** [comment]
The latest versions of paramiko install Cryptography for me (and a brief test showed it worked fine). However, the Fabric3 setup file currently has this:

    install_requires=['paramiko>=1.17.2,<2.0']

And paramiko version 1.17.2 uses PyCrypto.

**Comment by mathiasertl** [comment]
This is in line with what upstream Fabric did in 1.12. I port the changes from 1.13 ASAP, which will solve those issues.

**Comment by kbarnes3** [comment]
Porting 1.13 sounds like the best way to fix this, thanks. In the meantime, if anyone else hits this issue, I got a working combination by adding these lines to my requirements:

    git+https://github.com/dlitz/pycrypto.git@v2.7a1#egg=pycrypto
    Fabric3==1.12.post1

**Comment by mathiasertl** [comment]
Fabric3 1.13.1.post1 was release yesterday. I hope this solves the issue for you, if not, please file a new ticket (since it's most likely a new problem).

**Comment by kbarnes3** [comment]
I blew away my venv and freshly installed Fabric3 1.13.1.post1. I was able to run my fabfile without any problems and without explicitly installing any dependencies. Thanks @mathiasertl!
