### ISSUE TITLE
Use Paramiko 2.x

### ISSUE THREAD

**Issue by BYK** [mathiasertl/fabric#22]
Hey there,

Noticed you've pinned Paramiko to pre-2.x which still uses the deprecated and hard to install PyCrypto module. I wanted to submit a PR that uses the new 2.x line which replaced PyCrypto with Cryptography but didn't want to do it before I understand the reasons for pinning to a pre-2.x version.

Is there anything else holding us back? Paramiko docs say the new line is fully-backwards compatible in terms of API.

**Comment by mathiasertl** [comment]
Hey!

This originally came up in #14 - So we do it because this is what upstream does.

I'm happy to use paramiko 2.x if it requires few changes to the upstream source. In general, I try to keep changes to upstream to a minimum, in order to make it easier for me to merge in new releases...

**Comment by BYK** [comment]
@mathiasertl - oh, sorry. I went through some commits but not old issues/PRs :)

I currently can't install Fabric3 because of this reason. I can try locally and see if it breaks anything?

**Comment by johnzimm** [comment]
It looks like 1.13.1 in upstream now uses Paramiko 2.x: https://github.com/fabric/fabric/blob/master/sites/www/changelog.rst#id9

**Comment by mathiasertl** [comment]
I released Fabric3 1.13.1.post1 yesterday. An upgrade will install paramiko 2.0.
