### ISSUE TITLE
Versioning tweaks

### ISSUE THREAD

**Issue by nicktimko** [mathiasertl/fabric#4]
Assuming that Fabric 2.x will support Python 3, maybe you could rearrange the version numbers to avoid .postX, a la:

* Fabric 1.10.2post2 &rarr; Fabric3 10.2.2
* Fabric 1.11.9 &rarr; Fabric3 11.9.0

**Comment by mathiasertl** [comment]
AFAIK the upstream developer is not planning for something called "Fabric 2", the successor will have a different name.

In any case I do not understand your rationale for changing the versioning:

1. What's wrong with `postX`? It's not exactly what the suffix was intended for, but it still clearly states what version the `Fabric3` version is based on. `10.2.2` does not.
2. There is no `Fabric 1.10.2post2` (like in your example) only `Fabric 1.10.2` and `Fabric3 1.10.2.post1`.

**Comment by nicktimko** [comment]
I thought it was just going to be Fabric 2.0 whenever Jeff decides to un-private the branch. Is the "different name" you're thinking of Invoke (which is supposedly part of Fab 2)?

The x.y.z is *slightly* more [semver](http://semver.org/) than 1.x.y.postz, but version numbering is a very opinion-driven thing. This was mostly a take-it-or-leave-it suggestion, your discretion :)

**Comment by mathiasertl** [comment]
Yes, I think it was invoke. Reading up on it, `invoke` is apparently a split of parts of Fabrics components and Fabric2 will be using it. That being said I couldn't find any existing repository for it but an alpha/beta is due out within this month, this month being [May 2014](https://twitter.com/bitprophet/status/468082051842064384), [Aug 2014](https://github.com/fabric/fabric/issues/1050#issuecomment-51119847), [Sep 2015](https://github.com/fabric/fabric/issues/1378#issuecomment-139917737) or whatever.

Python/pip btw. has its own versioning recommendations, [PEP 0440](https://www.python.org/dev/peps/pep-0440), which gives only a limited list of possible suffixes. I know that using a `dev` suffix will cause pip not to install the version unless you give the `--pre` parameter. I certainly didn't want to end up with a version that would not automatically install. :-)

I guess I'll stick with the current versioning theme.

**Comment by nicktimko** [comment]
Oh, thought I commented/closed it a while ago... Was unfamiliar that [PEP-440 also spelled out post-releases and the `postX` suffix](https://www.python.org/dev/peps/pep-0440/#post-releases) as a thing. Never mind this issue :)
