### ISSUE TITLE
Differences between Fabrik 2 and Fabrik3?

### ISSUE THREAD

**Issue by dacog** [mathiasertl/fabric#52]
Hi, 

I've been reading about [Fabrik](https://github.com/fabric/fabric/) (version 1 and 2)  and [Fabrik3](https://github.com/mathiasertl/fabric), and I fail to understand the difference. 

In Fabrik's Readme it states 

> Fabric is a high level Python (2.7, 3.4+) library 

which from what see now does what Fabrik3 was trying to solve (Python3 compatibility).

I read [differences-with-fabric](https://github.com/mathiasertl/fabric#differences-with-fabric) on the Readme but I'm not sure if those differences are up-to-date.

Any other differences I should be aware of before deciding between Fabric2 or Fabric3?

Thanks!

**Comment by mathiasertl** [comment]
First: the software is called Fabri**c** :-)

In any case: This project is a fork of Fabric 1.x with Python 3 compatibility. It was started since Fabric 2.x was promised but never release for years.

Now that Fabric 2.x is out, please definitely use Fabric 2.x!
