### ISSUE TITLE
/bin/sh: 1: workon: not found

### ISSUE THREAD

**Issue by sac7e** [mathiasertl/fabric#9]
how to use fabric3 along with virtualenvwrapper? it seems the `with prefix()` in fabric doesn't work here.

**Comment by mathiasertl** [comment]
Hi! Does it work with the original Fabric? What is the error message you get?

**Comment by sibe7691** [comment]
@sac7e Any solution?

**Comment by mathiasertl** [comment]
If you want me to fix this issue, I need to know:

* Does it work with the original Fabric?
* What exactly doesn't work? "doesn't work here" is not exactly a detailed bugreport.
* Exact steps to reproduce.

**Comment by bittner** [comment]
When `with prefix()` doesn't work then there must be a problem with [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/). Usually, that translates to: the `VIRTUALENVWRAPPER_SCRIPT` has not been sourced. Make sure you've placed the 3 lines described in the [setup instructions](https://virtualenvwrapper.readthedocs.io/en/latest/install.html#shell-startup-file) in the right Shell Startup File (add debug output or whatever to find out).

## If You Want to Understand Why

Remind yourself that [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/#shell-aliases) is just a collection of shell functions, *and* that [with prefix()](https://github.com/fabric/fabric/blob/master/fabric/context_managers.py#L415) is not doing anything else than prefixing `<your-string-in-the-prefix-context-manager-call> && ` to all shell commands you're running with it.

**Comment by bittner** [comment]
It could be a good idea to avoid excessive trouble shooting (and headache) by removing *virtualenvwrapper* from your server requirements alltogether, and code the most needed functions from it in Python. This will probably be `workon` only anyway for 99% of you guys and lads. And this is equivalent to:
``` python
with prefix('<path/to/your/venv>bin/activate && cd <path/to/your/project>')
    # your code
```

**Comment by mathiasertl** [comment]
@bittner Thanks for the elaborate explanation! I'm closing this now, as this is not a fabric issue. I just want to add you can also use multiple context managers in a single with-stmt:

```
with prefix('<path/to/your/venv>/bin/activate'), cd('<path/to/your/project>'):
    # commands that need to be run in virtual environment
```
